### ISSUE TITLE
proposiciones 

### ISSUE THREAD

**Issue by chelui5** [SistemasTecTlaxiaco/actividad-7-proposiciones-l-gicas-chelui5#1]
[PROPOSICIONES .pdf](https://github.com/user-attachments/files/17441178/PROPOSICIONES.pdf)

**Comment by Eddi3mendoz** [comment]
Portada:25/25
Procedimiento:25/25
Figuras, Ilustraciones y Fotografías:25/25
Resultados y conclusiones:25/25
Calificación: 20/20

**Comment by josealfredo79** [comment]
bien hecho y revisado...
